background #332f50
foreground #fad6da

cursor #fad6da

selection_background #fad6da
selection_foreground #1c2023

color0 #8d7da1
color8 #8d7da1

color1 #fe90b3
color9 #fe90b3

color2 #7caa9d
color10 #7caa9d

color3 #f5e1c0
color11 #f5e1c0

color4 #8190b1
color12 #8190b1

color5 #cfaacc
color13 #cfaacc

color6 #acbebe
color14 #acbebe

color7 #f3f4f5
color15 #fad6da
